# Generated by Django 6.0 on 2025-12-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ no formato 00.000.000/0000-00', max_length=18, null=True, unique=True),
        ),
    ]
