# Generated by Django 6.0 on 2025-12-22 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='configuracao', serialize=False, to='empresas.empresa')),
                ('smtp_host', models.CharField(blank=True, max_length=255, verbose_name='Servidor SMTP')),
                ('smtp_porta', models.IntegerField(default=587, verbose_name='Porta')),
                ('smtp_usuario', models.CharField(blank=True, max_length=255, verbose_name='Usuário')),
                ('smtp_senha', models.CharField(blank=True, max_length=512, verbose_name='Senha')),
                ('smtp_usar_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('smtp_email_remetente', models.EmailField(blank=True, max_length=254, verbose_name='Email Remetente')),
                ('smtp_nome_remetente', models.CharField(blank=True, default='ForgeReports', max_length=255, verbose_name='Nome do Remetente')),
                ('smtp_testado_em', models.DateTimeField(blank=True, null=True)),
                ('smtp_ultimo_teste_ok', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
                'verbose_name_plural': 'Configurações das Empresas',
                'db_table': 'configuracoes_empresa',
            },
        ),
    ]
