# Generated by Django 5.2.4 on 2025-07-29 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Conexão')),
                ('tipo_banco', models.CharField(choices=[('sqlserver', 'SQL Server'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('oracle', 'Oracle')], max_length=20, verbose_name='Tipo de Banco')),
                ('servidor', models.CharField(max_length=200, verbose_name='Servidor')),
                ('banco', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuário')),
                ('senha', models.CharField(max_length=200, verbose_name='Senha')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Conexão de Banco de Dados',
                'verbose_name_plural': 'Conexões de Banco de Dados',
                'ordering': ['nome'],
            },
        ),
    ]
