# Generated by Django 5.2.4 on 2025-12-15 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conexoes', '0001_initial'),
        ('empresas', '0002_empresa_cnpj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('query_sql', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('limite_linhas_tela', models.IntegerField(default=1000)),
                ('permite_exportar', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conexao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conexoes.conexao')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'db_table': 'relatorios',
                'unique_together': {('empresa', 'nome')},
            },
        ),
    ]
