# Generated by Django 6.0 on 2025-12-16 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parametro', models.CharField(help_text='Nome do parâmetro na query (ex: @data_inicio)', max_length=100)),
                ('label', models.CharField(help_text='Label exibido ao usuário', max_length=255)),
                ('tipo', models.CharField(choices=[('DATA', 'Data'), ('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('LISTA', 'Lista')], max_length=20)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('valor_padrao', models.CharField(blank=True, max_length=255)),
                ('opcoes', models.JSONField(blank=True, help_text='Lista de opções para tipo LISTA', null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros', to='relatorios.relatorio')),
            ],
            options={
                'db_table': 'filtros',
                'ordering': ['ordem'],
                'unique_together': {('relatorio', 'parametro')},
            },
        ),
    ]
