# Generated by Django 5.2.4 on 2025-12-16 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_filtro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('VISUALIZAR', 'Visualizar'), ('EXPORTAR', 'Exportar')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='relatorios.relatorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_relatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permissoes',
                'unique_together': {('relatorio', 'usuario')},
            },
        ),
    ]
