# Generated by Django 6.0 on 2025-12-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0004_pasta_relatorio_pasta_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtro',
            name='formato_data',
            field=models.CharField(blank=True, help_text='Formato de conversão da data (ex: %Y%m%d)', max_length=100),
        ),
    ]
