# Generated by Django 5.2.4 on 2025-12-15 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_cnpj'),
        ('relatorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filtros_usados', models.JSONField(blank=True, null=True)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(null=True)),
                ('tempo_execucao_ms', models.IntegerField(null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True, null=True)),
                ('qtd_linhas', models.IntegerField(null=True)),
                ('exportou', models.BooleanField(default=False)),
                ('exportado_em', models.DateTimeField(null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.relatorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'execucoes',
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
