# Generated by Django 5.2.4 on 2025-07-29 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Relatório')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('sql_query', models.TextField(verbose_name='Query SQL')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conexao_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connections.databaseconnection', verbose_name='Conexão do Banco')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('usuarios_permitidos', models.ManyToManyField(blank=True, related_name='reports_permitidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Permitidos')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ReportFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Filtro')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('select', 'Lista de Opções'), ('data', 'Data')], max_length=20, verbose_name='Tipo do Filtro')),
                ('opcoes_select', models.JSONField(blank=True, null=True, verbose_name='Opções do Select')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros', to='reports.report', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Filtro de Relatório',
                'verbose_name_plural': 'Filtros de Relatórios',
                'ordering': ['relatorio', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ReportFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Pasta')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('pasta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.reportfolder', verbose_name='Pasta Pai')),
            ],
            options={
                'verbose_name': 'Pasta de Relatórios',
                'verbose_name_plural': 'Pastas de Relatórios',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportfolder', verbose_name='Pasta'),
        ),
    ]
