# Generated by Django 5.2.4 on 2025-12-14 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome descritivo da conexão', max_length=255)),
                ('tipo', models.CharField(choices=[('SQLSERVER', 'SQL Server'), ('POSTGRESQL', 'PostgreSQL'), ('MYSQL', 'MySQL')], help_text='Tipo do banco de dados', max_length=20)),
                ('host', models.CharField(help_text='Servidor/hostname do banco', max_length=255)),
                ('porta', models.IntegerField(help_text='Porta de conexão')),
                ('database', models.CharField(help_text='Nome do database', max_length=255)),
                ('usuario', models.CharField(help_text='Usuário do banco', max_length=255)),
                ('senha_encriptada', models.TextField(help_text='Senha criptografada (AES)')),
                ('ativo', models.BooleanField(default=True, help_text='Conexão ativa?')),
                ('ultimo_teste_em', models.DateTimeField(blank=True, help_text='Data/hora do último teste de conexão', null=True)),
                ('ultimo_teste_ok', models.BooleanField(blank=True, help_text='Resultado do último teste (True=sucesso, False=falha, None=nunca testado)', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Conexão',
                'verbose_name_plural': 'Conexões',
                'db_table': 'conexoes',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
    ]
