# Generated by Django 6.0 on 2025-12-22 02:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_add_configuracao_empresa'),
        ('execucoes', '0001_initial'),
        ('relatorios', '0005_filtro_formato_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('frequencia', models.CharField(choices=[('DIARIO', 'Diário'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')], max_length=20)),
                ('hora_execucao', models.TimeField(help_text='Horário de execução (HH:MM:SS)')),
                ('dias_semana', models.JSONField(blank=True, help_text='Lista de dias [0-6] para semanal (0=Domingo)', null=True)),
                ('dia_mes', models.IntegerField(blank=True, help_text='Dia do mês [1-31] para mensal', null=True)),
                ('filtros_padrao', models.JSONField(blank=True, help_text='Valores para os filtros do relatório', null=True)),
                ('enviar_email', models.BooleanField(default=True)),
                ('emails_destino', models.JSONField(default=list, help_text='Lista de emails destinatários')),
                ('ativo', models.BooleanField(default=True)),
                ('proxima_execucao', models.DateTimeField(blank=True, null=True)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='empresas.empresa')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='relatorios.relatorio')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'agendamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoAgendada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True, null=True)),
                ('email_enviado', models.BooleanField(default=False)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_execucoes', to='agendamentos.agendamento')),
                ('execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='execucoes.execucao')),
            ],
            options={
                'verbose_name': 'Execução Agendada',
                'verbose_name_plural': 'Execuções Agendadas',
                'db_table': 'execucoes_agendadas',
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
